### ISSUE TITLE
Aside from ProTally: ATEM-TSL Bridge

### ISSUE THREAD

**Issue by Keksstar** [josephdadams/ProTally#1]
Hi Joseph,

just wanted to ask if you could create an ATEM-TSL converter with your knowledge in programming? Getting the Tally Information (and the source name if possible?) and send them to TSL 3.1?
This would be great for working with Decimator DMON-Quad and other TSL displays :-)

Please let me know!

Thanks,
Andreas

**Comment by josephdadams** [comment]
Sure! Essentially every tally protocol ProTally supports is being converted to a TSL-like object already. How would you want to receive that TSL data? UDP, TCP, or a choice in the app? I don’t own an ATEM, is this something you could help test?

**Comment by Keksstar** [comment]
Would be great if it could be defined if you either want TCP or UDP. Me personally is using an RS485 modem with accepts both for sending to the Decimator. But maybe other people are using other products :)  I can help in testing as I have both devices.
Thanks for your help with this!

**Comment by josephdadams** [comment]
So I think I would create this where in the Bridge, you can connect to the ATEM, and then it relays the tally data back out in TSL format to a user-configured IP address, port, and choice of TCP/UDP. Supporting sending the data to multiple devices shouldn't be a problem. Would that work for you? I don't know how you then pick it up and get it into the RS485 modem. I don't know anything about those.

**Comment by Keksstar** [comment]
That would absolutely fine. Don´t worry about the "electrical" part.
In a later step maybe you can add "address mapping" where the user can decide which ATEM input goes to which TSL address? As you already have in ProTally.

**Comment by Keksstar** [comment]
That would absolutely fine. Don´t worry about the "electrical" part.
In a later step maybe you can add "address mapping" where the user can decide which ATEM input goes to which TSL address? As you already have in ProTally.

**Comment by Keksstar** [comment]
Hi Joseph, just wanted to ask if you already had the time to look into this?

**Comment by josephdadams** [comment]
Nope

**Comment by josephdadams** [comment]
@Keksstar I am going to close this. I have too many other projects going on right now, and since I don’t own or use an ATEM, there is nothing pushing this to the top. Best of luck.

**Comment by josephdadams** [comment]
@Keksstar just wanted to ping you to take a look at my other project, Tally Arbiter. It can take ATEM tally in and send TSL out. It might work for what you requested.
