### ISSUE TITLE
Roland Smart Tally with an Invalid IP causes an exception

### ISSUE THREAD

**Issue by MichaelAllen** [josephdadams/ProTally#2]
If I try to connect to an invalid IP, or the switcher happens to be turned off, I get an exception that `notify.log()` is not a function. The only way I have found to get back into the program is to edit the preferences file under `~/Library/ApplicationSupport/ProTally/user-prefernces.json` and take out the invalid address.

It looks like the problem is a simple fix. `notify.log()` should actually be `notify()`. I will submit a pull request to fix this.

<img width="350" src="https://user-images.githubusercontent.com/282879/61570808-14411200-aa5d-11e9-8b2c-100f3d145661.png">

**Comment by josephdadams** [comment]
Great catch! Thanks! I'll look for your PR and I can release a bugfix build.
